### ISSUE TITLE
Muzzle should recognise mismatch on unimplemented abstract methods at runtime

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-java-instrumentation#1337]
This is related to: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/1123

I have a custom Servlet instrumentation that wraps request/response to read bodies (similar to https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1167). The instrumentation works well with servlet 3.0 however the instrumentation does not implement `'abstract boolean isReady()' of abstract class javax.servlet.ServletInputStream` and hence it fails at runtime for servlet 3.1. 

The buil
d with muzzle gradle plugin correctly fails. 
```bash

> Task :instrumentation:servlet:servlet-3.0:muzzle-AssertPass-javax.servlet-javax.servlet-api-3.1.0 FAILED
FilterChain advice
FAILED MUZZLE VALIDATION: io.opentelemetry.instrumentation.auto.servlet.v3_0.bodycapture.Servlet3BodyInstrumentation mismatches:
-- io.opentelemetry.instrumentation.auto.servlet.v3_0.bodycapture.BufferingHttpServletRequest$ServletInputStreamWrapper:263 Missing method javax.servlet.ServletInputStream#isFinished()Z
-- io.opentelemetry.instrumentation.auto.servlet.v3_0.bodycapture.BufferingHttpServletRequest$ServletInputStreamWrapper:263 Missing method javax.servlet.ServletInputStream#isReady()Z
-- io.opentelemetry.instrumentation.auto.servlet.v3_0.bodycapture.BufferingHttpServletRequest$ServletInputStreamWrapper:263 Missing method javax.servlet.ServletInputStream#setReadListener(Ljavax/servlet/ReadListener;)V
-- io.opentelemetry.instrumentation.auto.servlet.v3_0.bodycapture.BufferingHttpServletResponse:68 Missing method javax.servlet.ServletOutputStream#isReady()Z
-- io.opentelemetry.instrumentation.auto.servlet.v3_0.bodycapture.BufferingHttpServletResponse:68 Missing method javax.servlet.ServletOutputStream#setWriteListener(Ljavax/servlet/WriteListener;)V

> Task :instrumentation:servlet:servlet-3.0:muzzle-AssertPass-javax.servlet-javax.servlet-api-4.0.1 FAILED
FilterChain advice
FAILED MUZZLE VALIDATION: io.opentelemetry.instrumentation.auto.servlet.v3_0.bodycapture.Servlet3BodyInstrumentation mismatches:
-- io.opentelemetry.instrumentation.auto.servlet.v3_0.bodycapture.BufferingHttpServletRequest$ServletInputStreamWrapper:263 Missing method javax.servlet.ServletInputStream#isFinished()Z
-- io.opentelemetry.instrumentation.auto.servlet.v3_0.bodycapture.BufferingHttpServletRequest$ServletInputStreamWrapper:263 Missing method javax.servlet.ServletInputStream#isReady()Z
-- io.opentelemetry.instrumentation.auto.servlet.v3_0.bodycapture.BufferingHttpServletRequest$ServletInputStreamWrapper:263 Missing method javax.servlet.ServletInputStream#setReadListener(Ljavax/servlet/ReadListener;)V
-- io.opentelemetry.instrumentation.auto.servlet.v3_0.bodycapture.BufferingHttpServletResponse:68 Missing method javax.servlet.ServletOutputStream#isReady()Z
-- io.opentelemetry.instrumentation.auto.servlet.v3_0.bodycapture.BufferingHttpServletResponse:68 Missing method javax.servlet.ServletOutputStream#setWriteListener(Ljavax/servlet/WriteListener
```

Ideally, the muzzle matcher should also recognize mismatch at runtime and prevent instrumentation from being loaded.

**Comment by mateuszrzeszutek** [comment]
Hmm, so at runtime muzzle allows this instrumentation to happen? That's pretty strange - muzzle compile task and `MuzzleMatcher` call pretty much the same method. Have you tried turning the debug logging on? Does `MuzzleMatcher` log anything?
Also, if it's possible please provide an example -- a draft PR, unit test, whatever that allows reproducing this issue.

**Comment by devinsba** [comment]
Unrelated to your issue, but I would warn against wrapping servlet types. I have run into issues where some application servers will cast to a concrete type so wrapping will break these servers

**Comment by pavolloffay** [comment]
Agree, it's not the easiest feature to implement. @devinsba do you remember which app servlet/servlet container is casting to specific types?

**Comment by devinsba** [comment]
It was Oracle WebLogic Server, the version in my downloads folder is `10.3.6.0`

**Comment by iNikem** [comment]
> Agree, it's not the easiest feature to implement. @devinsba do you remember which app servlet/servlet container is casting to specific types?

Even Jetty does that

**Comment by pavolloffay** [comment]
@mateuszrzeszutek here is the reproducer https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1354

**Comment by mateuszrzeszutek** [comment]
Thanks! I'll take a look at it right away
