### ISSUE TITLE
Duplicate class definition of ContextDataProvider 

### ISSUE THREAD

**Issue by pleeplop** [open-telemetry/opentelemetry-java-instrumentation#5466]
**Describe the bug**
Log4j2InstrumentationModule used in javaagent version 1.11.0 throws java.lang.ClassNotFoundException when loading org.apache.logging.log4j.core.util.ContextDataProvider.
It was working in version 1.10.0

Log4j2InstrumentationModule defined as TypeMatcher the class ContextDataProvider but a class injected also implements ContextDataProvider causing the interface to be loaded while it's being transformed, which leads to duplicate class definition error after the interface is transformed and the triggering class loader tries to load it.

This issue was already known (see the comments of the previous version) https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/5216/files#diff-0225235d7840055cce2f3782f412db7bae6c574d862c59d5e78e53669994cfd3

Instrumentation works again if i revert this change https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/5216/ 

**Steps to reproduce**
You should be able to reproduce it with javaagent and log4j2. Let me know if you need more details.

**What did you expect to see?**
I will expect to be able to load log4j-context-data-2.16 instrumentation module with javaagent.

**What did you see instead?**
```
[otel.javaagent 2022-02-28 10:41:48:273 +0100] [Start Level: Equinox Container: 752c254d-46c0-4b48-9525-2d6dea8a0e2f] ERROR io.opentelemetry.javaagent.tooling.HelperInjector - Error preparing helpers while processing interface org.apache.logging.log4j.core.util.ContextDataProvider for log4j-context-data. Failed to inject helper classes into instance org.eclipse.osgi.internal.loader.EquinoxClassLoader@81f7bf7[org.ops4j.pax.logging.pax-logging-log4j2:2.0.14(id=7)]
java.lang.IllegalStateException: java.lang.NoClassDefFoundError: org/apache/logging/log4j/core/util/ContextDataProvider
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$UsingUnsafeInjection.defineClass(ClassInjector.java:1044)
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.injectRaw(ClassInjector.java:283)
	at io.opentelemetry.javaagent.tooling.HelperInjector.injectClassLoader(HelperInjector.java:262)
	at io.opentelemetry.javaagent.tooling.HelperInjector.lambda$injectHelperClasses$2(HelperInjector.java:211)
	at io.opentelemetry.javaagent.shaded.instrumentation.api.cache.internal.weaklockfree.AbstractWeakConcurrentMap.lambda$computeIfAbsent$0(AbstractWeakConcurrentMap.java:177)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at io.opentelemetry.javaagent.shaded.instrumentation.api.cache.internal.weaklockfree.AbstractWeakConcurrentMap.computeIfAbsent(AbstractWeakConcurrentMap.java:177)
	at io.opentelemetry.javaagent.shaded.instrumentation.api.cache.internal.weaklockfree.WeakConcurrentMap.computeIfAbsent(WeakConcurrentMap.java:48)
	at io.opentelemetry.javaagent.shaded.instrumentation.api.cache.internal.weaklockfree.WeakConcurrentMap$WithInlinedExpunction.computeIfAbsent(WeakConcurrentMap.java:206)
	at io.opentelemetry.javaagent.shaded.instrumentation.api.cache.WeakLockFreeCache.computeIfAbsent(WeakLockFreeCache.java:21)
	at io.opentelemetry.javaagent.tooling.HelperInjector.injectHelperClasses(HelperInjector.java:199)
	at io.opentelemetry.javaagent.tooling.HelperInjector.transform(HelperInjector.java:155)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:11755)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:11692)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1700(AgentBuilder.java:11405)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$Java9CapableVmDispatcher.run(AgentBuilder.java:12172)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$Java9CapableVmDispatcher.run(AgentBuilder.java:12104)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doPrivileged(AgentBuilder.java)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:11633)
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$ByteBuddy$ModuleSupport.transform(Unknown Source)
	at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.defineClass(ModuleClassLoader.java:293)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.defineClass(ClasspathManager.java:718)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findClassImpl(ClasspathManager.java:641)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClassImpl(ClasspathManager.java:609)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClassImpl(ClasspathManager.java:589)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:568)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:345)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:401)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:480)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:170)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.defineClass(ModuleClassLoader.java:293)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.defineClass(ClasspathManager.java:718)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findClassImpl(ClasspathManager.java:641)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClassImpl(ClasspathManager.java:609)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClassImpl(ClasspathManager.java:589)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:568)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:345)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:401)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:480)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:170)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.ops4j.pax.logging.log4j2.internal.Activator.start(Activator.java:88)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:814)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:806)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:763)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1028)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:371)
	at org.eclipse.osgi.container.Module.doStart(Module.java:605)
	at org.eclipse.osgi.container.Module.start(Module.java:468)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1849)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1842)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1785)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1747)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1669)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
Caused by: java.lang.NoClassDefFoundError: org/apache/logging/log4j/core/util/ContextDataProvider
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.lang.ClassLoader$ByteBuddyAccessor$SXO8JhPq.defineClass(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$UsingUnsafeInjection.defineClass(ClassInjector.java:1040)
	... 67 more
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.core.util.ContextDataProvider cannot be found by org.ops4j.pax.logging.pax-logging-log4j2_2.0.14
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:519)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:170)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 75 more
```

**What version are you using?**
1.11.0

**Environment**
Compiler: OpenJDK  Zulu11.54+23-CA (build 11.0.14+9-LTS)
OS: Ubuntu 20.04

**Comment by trask** [comment]
hi @pleeplop! can you provide a repro that we can use to troubleshoot the issue? we thought that we had fixed the "Duplicate class definition" issue which is why we removed the previous workaround, and we aren't able to reproduce the error you are seeing anymore, at least in our integration tests, so if you can provide a repro that would be really helpful, thx!

**Comment by pleeplop** [comment]
Hi @trask ,
Thanks for the feedback.

Here is the procedure to reproduce the issue:
- Download/extract karaf application: http://www.apache.org/dyn/closer.lua/karaf/4.3.6/apache-karaf-4.3.6.tar.gz
- Apply some config: `echo "karaf.framework=equinox" >>  apache-karaf-4.3.6/etc/config.properties`
- Run karaf `KARAF_OPTS="-javaagent:/path/to/opentelemetry-javaagent-1.10.1.jar" apache-karaf-4.3.6/bin/karaf`

You should see the exception in the console:
```
[otel.javaagent 2022-03-07 09:17:27:304 +0100] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 1.11.1
[otel.javaagent 2022-03-07 09:17:32:686 +0100] [Start Level: Equinox Container: e44d0bf6-23b5-4904-9ef9-46f44cba852e] ERROR io.opentelemetry.javaagent.tooling.HelperInjector - Error preparing helpers while processing interface org.apache.logging.log4j.core.util.ContextDataProvider for log4j-context-data. Failed to inject helper classes into instance org.eclipse.osgi.internal.loader.EquinoxClassLoader@1d300b7b[org.ops4j.pax.logging.pax-logging-log4j2:2.0.14(id=7)]
java.lang.IllegalStateException: java.lang.NoClassDefFoundError: org/apache/logging/log4j/core/util/ContextDataProvider
        at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$UsingUnsafeInjection.defineClass(ClassInjector.java:1044)
        at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.injectRaw(ClassInjector.java:283)
        at io.opentelemetry.javaagent.tooling.HelperInjector.injectClassLoader(HelperInjector.java:262)
        at io.opentelemetry.javaagent.tooling.HelperInjector.lambda$injectHelperClasses$2(HelperInjector.java:211)
        at io.opentelemetry.javaagent.shaded.instrumentation.api.cache.internal.weaklockfree.AbstractWeakConcurrentMap.lambda$computeIfAbsent$0(AbstractWeakConcurrentMap.java:177)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
        at io.opentelemetry.javaagent.shaded.instrumentation.api.cache.internal.weaklockfree.AbstractWeakConcurrentMap.computeIfAbsent(AbstractWeakConcurrentMap.java:177)
        at io.opentelemetry.javaagent.shaded.instrumentation.api.cache.internal.weaklockfree.WeakConcurrentMap.computeIfAbsent(WeakConcurrentMap.java:48)
        at io.opentelemetry.javaagent.shaded.instrumentation.api.cache.internal.weaklockfree.WeakConcurrentMap$WithInlinedExpunction.computeIfAbsent(WeakConcurrentMap.java:206)
        at io.opentelemetry.javaagent.shaded.instrumentation.api.cache.WeakLockFreeCache.computeIfAbsent(WeakLockFreeCache.java:21)
        at io.opentelemetry.javaagent.tooling.HelperInjector.injectHelperClasses(HelperInjector.java:199)
        at io.opentelemetry.javaagent.tooling.HelperInjector.transform(HelperInjector.java:155)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:11755)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:11692)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1700(AgentBuilder.java:11405)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$Java9CapableVmDispatcher.run(AgentBuilder.java:12172)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$Java9CapableVmDispatcher.run(AgentBuilder.java:12104)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doPrivileged(AgentBuilder.java)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:11633)
        at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$ByteBuddy$ModuleSupport.transform(Unknown Source)
        at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.defineClass(ModuleClassLoader.java:293)
        at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.defineClass(ClasspathManager.java:718)
        at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findClassImpl(ClasspathManager.java:641)
        at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClassImpl(ClasspathManager.java:609)
        at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClassImpl(ClasspathManager.java:589)
        at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:568)
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:345)
        at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:401)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:480)
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:170)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.defineClass(ModuleClassLoader.java:293)
        at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.defineClass(ClasspathManager.java:718)
        at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findClassImpl(ClasspathManager.java:641)
        at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClassImpl(ClasspathManager.java:609)
        at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClassImpl(ClasspathManager.java:589)
        at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:568)
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:345)
        at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:401)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:480)
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:170)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at org.ops4j.pax.logging.log4j2.internal.Activator.start(Activator.java:88)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:814)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:1)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:806)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:763)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1028)
        at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:371)
        at org.eclipse.osgi.container.Module.doStart(Module.java:605)
        at org.eclipse.osgi.container.Module.start(Module.java:468)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1849)
        at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1842)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1785)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1747)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1669)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
Caused by: java.lang.NoClassDefFoundError: org/apache/logging/log4j/core/util/ContextDataProvider
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at java.base/java.lang.ClassLoader$ByteBuddyAccessor$v1OYoAMa.defineClass(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$UsingUnsafeInjection.defineClass(ClassInjector.java:1040)
        ... 67 more
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.core.util.ContextDataProvider cannot be found by org.ops4j.pax.logging.pax-logging-log4j2_2.0.14
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:519)
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:170)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 75 more
```

**Comment by trask** [comment]
@pleeplop thanks for reporting this! it should be fixed in 1.12.0 which is currently planned for end of this week
