### PR TITLE
Muzzle should recognise mismatch on unimplemented abstract methods at runtime

### LINKED ISSUE #1337: Muzzle should recognise mismatch on unimplemented abstract methods at runtime
This is related to: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/1123

I have a custom Servlet instrumentation that wraps request/response to read bodies (similar to https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1167). The instrumentation works well with servlet 3.0 however the instrumentation does not implement `'abstract boolean isReady()' of abstract class javax.servlet.ServletInputStream` and hence it fails at runtime for servlet 3.1. 

The buil
d with muzzle gradle plugin correctly fails. 
```bash

> Task :instrumentation:servlet:servlet-3.0:muzzle-AssertPass-javax.servlet-javax.servlet-api-3.1.0 FAILED
FilterChain advice
FAILED MUZZLE VALIDATION: io.opentelemetry.instrumentation.auto.servlet.v3_0.bodycapture.Servlet3BodyInstrumentation mismatches:
-- io.opentelemetry.instrumentation.auto.servlet.v3_0.bodycapture.BufferingHttpServletRequest$ServletInputStreamWrapper:263 Missing method javax.servlet.ServletInputStream#isFinished()Z
-- io.opentelemetry.instrumentation.auto.servlet.v3_0.bodycapture.BufferingHttpServletRequest$ServletInputStreamWrapper:263 Missing method javax.servlet.ServletInputStream#isReady()Z
-- io.opentelemetry.instrumentation.auto.servlet.v3_0.bodycapture.BufferingHttpServletRequest$ServletInputStreamWrapper:263 Missing method javax.servlet.ServletInputStream#setReadListener(Ljavax/servlet/ReadListener;)V
-- io.opentelemetry.instrumentation.auto.servlet.v3_0.bodycapture.BufferingHttpServletResponse:68 Missing method javax.servlet.ServletOutputStream#isReady()Z
-- io.opentelemetry.instrumentation.auto.servlet.v3_0.bodycapture.BufferingHttpServletResponse:68 Missing method javax.servlet.ServletOutputStream#setWriteListener(Ljavax/servlet/WriteListener;)V

> Task :instrumentation:servlet:servlet-3.0:muzzle-AssertPass-javax.servlet-javax.servlet-api-4.0.1 FAILED
FilterChain advice
FAILED MUZZLE VALIDATION: io.opentelemetry.instrumentation.auto.servlet.v3_0.bodycapture.Servlet3BodyInstrumentation mismatches:
-- io.opentelemetry.instrumentation.auto.servlet.v3_0.bodycapture.BufferingHttpServletRequest$ServletInputStreamWrapper:263 Missing method javax.servlet.ServletInputStream#isFinished()Z
-- io.opentelemetry.instrumentation.auto.servlet.v3_0.bodycapture.BufferingHttpServletRequest$ServletInputStreamWrapper:263 Missing method javax.servlet.ServletInputStream#isReady()Z
-- io.opentelemetry.instrumentation.auto.servlet.v3_0.bodycapture.BufferingHttpServletRequest$ServletInputStreamWrapper:263 Missing method javax.servlet.ServletInputStream#setReadListener(Ljavax/servlet/ReadListener;)V
-- io.opentelemetry.instrumentation.auto.servlet.v3_0.bodycapture.BufferingHttpServletResponse:68 Missing method javax.servlet.ServletOutputStream#isReady()Z
-- io.opentelemetry.instrumentation.auto.servlet.v3_0.bodycapture.BufferingHttpServletResponse:68 Missing method javax.servlet.ServletOutputStream#setWriteListener(Ljavax/servlet/WriteListener
```

Ideally, the muzzle matcher should also recognize mismatch at runtime and prevent instrumentation from being loaded.

### PR DESCRIPTION
**Pull request by mateuszrzeszutek**
Fixes #1337

It turns out that `REFERENCE_CREATION_PACKAGE` value at runtime was completely different than at compile time: `relocate` changed the strings it was not supposed to change - see `exclude` below:

```groovy
  // rewrite library instrumentation dependencies
  relocate("io.opentelemetry.instrumentation", "io.opentelemetry.javaagent.shaded.instrumentation") {
    exclude "io.opentelemetry.instrumentation.auto.**"
  }
```

Thanks @pavolloffay for the repro steps!

### CODE REVIEW

**Review by trask — APPROVED** [review]
Thanks @pavolloffay @mateuszrzeszutek!

I created #1364 to add an integration test for this tricky behavior sometime in the future

**Comment by pavolloffay** [comment]
thanks @mateuszrzeszutek for looking into this 👍
